name: Linux

on:
  push:
    branches: [ main, testing, dev ]
  pull_request:
    branches: [ main, testing, dev ]

jobs:
  testLinux:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Packages (apt)
        run: |
          sudo apt update
          sudo apt install libenchant-dev qt5-default qttools5-dev-tools
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Dependencies (pip)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-timeout
          pip install pytest-cov
          pip install pytest-qt
          pip install codecov
      - name: Run Build Commands
        run: python setup.py qtlrelease sample
      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pytest -v --cov=nw --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
